### ISSUE TITLE
Hot-reloading doesn't work in this project.

### ISSUE THREAD

**Issue by thomasguo** [jooby-project/ebean-starter#3]
Hi @jknack ,

I just checked out all code of this project and simply run it:

mvn jooby:run

It works well as expected.   But if I modify any code in the App.java,   it doesn't recompile it hottly. And the console printed out error messages like these:

[INFO] Scanning for projects...
Exception in thread "HotswapScanner" javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory not found
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at groovy.xml.FactorySupport$2.run(FactorySupport.java:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at groovy.xml.FactorySupport.createFactory(FactorySupport.java:35)
        at groovy.xml.FactorySupport.createSaxParserFactory(FactorySupport.java:56)
        at groovy.util.XmlSlurper.<init>(XmlSlurper.java:128)
        at groovy.util.XmlSlurper.<init>(XmlSlurper.java:114)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
        at io.repaint.maven.tiles.TileModel$_strippedPom_closure2.doCall(TileModel.groovy:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.IOGroovyMethods.withReader(IOGroovyMethods.java:1183)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.withReader(ResourceGroovyMethods.java:1604)
        at org.codehaus.groovy.runtime.dgm$1027.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at io.repaint.maven.tiles.TileModel.strippedPom(TileModel.groovy:29)
        at io.repaint.maven.tiles.TileModel.loadTile(TileModel.groovy:52)
        at io.repaint.maven.tiles.TileModel.<init>(TileModel.groovy:57)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.loadModel(TilesMavenLifecycleParticipant.groovy:216)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.loadAllDiscoveredTiles(TilesMavenLifecycleParticipant.groovy:639)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.orchestrateMerge(TilesMavenLifecycleParticipant.groovy:338)
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRead(TilesMavenLifecycleParticipant.groovy:286)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.jooby.JoobyMojo.lambda$execute$2(JoobyMojo.java:208)
        at org.jooby.JoobyMojo.lambda$setupCompiler$4(JoobyMojo.java:292)
        at org.jooby.run.Watcher.processEvents(Watcher.java:142)
        at org.jooby.run.Watcher.lambda$new$0(Watcher.java:68)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: __redirected/__SAXParserFactory
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
        ... 48 more

**Comment by jknack** [comment]
Going to check again but should be fixed with: https://github.com/jooby-project/jooby/commit/1a8314cdb7f75edcc3fac5ffb999110bb7175b61

but isn;t released yet. going to release end of this week

**Comment by thomasguo** [comment]
@jknack 

So is there any update for this issue or new release?

**Comment by jknack** [comment]
It is fixed in master. Going to release 1.1.1 later this week

**Comment by jknack** [comment]
Also, it fails with Maven compiler. If you compile your source code with an IDE, it works.

**Comment by ajcamilo** [comment]
you also need to add this dependency and bump maven-compiler-plugin version (https://github.com/jooby-project/jooby/pull/746)

```
<dependency>
  <groupId>org.avaje</groupId>
  <artifactId>avaje-agentloader</artifactId>
  <scope>runtime</scope>
</dependency>
```

**Comment by jknack** [comment]
It works now.

btw/ going to close all issues here and remove the issues reporting tab from starter projects. If you find any new issue please report them to https://github.com/jooby-project/jooby
